In [114]:
pip install matplotlib

Requirement already satisfied: matplotlib in c:\users\luizreis\appdata\local\programs\python\python314\lib\site-packages (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\luizreis\appdata\local\programs\python\python314\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\luizreis\appdata\local\programs\python\python314\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\luizreis\appdata\local\programs\python\python314\lib\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\luizreis\appdata\local\programs\python\python314\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in c:\users\luizreis\appdata\local\programs\python\python314\lib\site-packages (from matplotlib) (2.4.3)
Requirement already satisfied: packaging>=20.0 in c:\users\luizreis\appdata\roaming\python\python314\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\luizreis\appdata\local\programs\python\python314\lib\site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\users\luizreis\appdata\local\programs\python\python314\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\luizreis\appdata\roaming\python\python314\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\luizreis\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [115]:
pip install nbformat

Requirement already satisfied: nbformat in c:\users\luizreis\appdata\local\programs\python\python314\lib\site-packages (5.10.4)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\luizreis\appdata\local\programs\python\python314\lib\site-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in c:\users\luizreis\appdata\local\programs\python\python314\lib\site-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\luizreis\appdata\roaming\python\python314\site-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in c:\users\luizreis\appdata\roaming\python\python314\site-packages (from nbformat) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\luizreis\appdata\local\programs\python\python314\lib\site-packages (from jsonschema>=2.6->nbformat) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\luizreis\appdata\local\programs\python\python314\lib\site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\luizreis\appdata\local\programs\python\python314\lib\site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\users\luizreis\appdata\local\programs\python\python314\lib\site-packages (from jsonschema>=2.6->nbformat) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\luizreis\appdata\roaming\python\python314\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.9.4)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [116]:
import pandas as pd 
import matplotlib as pl 
import datetime as pydt 
import plotly.graph_objects as go
import plotly.express as px

In [117]:
df = pd.read_csv("dataset_asimov.csv")

In [118]:
df

,Status de Pagamento,Dia,Mês,Meio de Propaganda,Valor Pago,Chamadas Realizadas,Duração da chamada,Modelo de Treinamento,Nivel de Treinamento,Código de Área,Equipe,Consultor
0,Pago,1,Abr,Televisão,R$ 7000000,3,02:00,GK,KJI. L4,A7,Equipe 1,Arthur
1,Pago,10,Ago,Televisão,R$ 11000000,1,02:00,GK,Pre. L8,B13,Equipe 2,Heitor
2,Pago,20,Set,Website,R$ 12000000,3,02:00,GK,Fndn. L5,A1,Equipe 2,Helena
3,Pago,23,Set,Facebook,R$ 15000000,1,02:00,GK,Fndn. L5,A2,Equipe 3,Alice
4,Pago,11,Set,Televisão,R$ 25000000,2,02:00,GK,Fndn. L3,B13,Equipe 4,Theo
...,...,...,...,...,...,...,...,...,...,...,...,...
1232,Não pago,18,Nov,Facebook,R$ 0,2,12:55,NaN,NaN,A1,Equipe 4,Theo
1233,Não pago,24,Nov,WhatsApp,R$ 0,2,12:55,NaN,NaN,A7,Equipe 2,Heitor
1234,Não pago,9,Dez,Televisão,R$ 0,1,12:55,NaN,NaN,A4,Equipe 2,Laura
1235,Não pago,11,Fev,Facebook,R$ 0,2,12:55,NaN,NaN,B18,Equipe 2,Laura
1236,Não pago,12,Mar,Televisão,R$ 0,2,12:55,NaN,NaN,B18,Equipe 3,Sophia

In [119]:
df_cru = df.copy()

In [120]:
df.loc[ df['Mês'] == 'Jan', 'Mês'] = "1"
df.loc[ df['Mês'] == 'Fev', 'Mês'] = "2"
df.loc[ df['Mês'] == 'Mar', 'Mês'] = "3"
df.loc[ df['Mês'] == 'Abr', 'Mês'] = "4"
df.loc[ df['Mês'] == 'Mai', 'Mês'] = "5"
df.loc[ df['Mês'] == 'Jun', 'Mês'] = "6"
df.loc[ df['Mês'] == 'Jul', 'Mês'] = "7"
df.loc[ df['Mês'] == 'Ago', 'Mês'] = "8"
df.loc[ df['Mês'] == 'Set', 'Mês'] = "9"
df.loc[ df['Mês'] == 'Out', 'Mês'] = "10"
df.loc[ df['Mês'] == 'Nov', 'Mês'] = "11"
df.loc[ df['Mês'] == 'Dez', 'Mês'] = "12"

In [121]:
df['Chamadas Realizadas'] = df['Chamadas Realizadas'].astype(int)
df['Dia'] = df['Dia'].astype(int)
df['Mês'] = df['Mês'].astype(int)

df['Valor Pago'] = df['Valor Pago'].str.lstrip('R$ ')
df['Valor Pago'] = df['Valor Pago'].astype(int)

In [122]:
df.loc[df['Status de Pagamento'] == 'Pago', 'Status de Pagamento'] = "1"
df.loc[df['Status de Pagamento'] == 'Não pago', 'Status de Pagamento'] = "0"
df['Status de Pagamento'] = df['Status de Pagamento'].astype(int)

In [125]:
options_month = [{'label' : 'Ano Todo', 'value' : 0}]
for i, j in zip(df_cru['Mês'].unique(), df['Mês'].unique()): 
    options_month.append({'label' : i, 'value' : int(j)})

options_month = sorted(options_month, key = lambda x: x['value'])

In [124]:
print(options_month)

[{'label': 'Ano Todo', 'value': 0}, {'label': 'Jan', 'value': 1}, {'label': 'Fev', 'value': 2}, {'label': 'Mar', 'value': 3}, {'label': 'Abr', 'value': 4}, {'label': 'Mai', 'value': 5}, {'label': 'Jun', 'value': 6}, {'label': 'Jul', 'value': 7}, {'label': 'Ago', 'value': 8}, {'label': 'Set', 'value': 9}, {'label': 'Out', 'value': 10}, {'label': 'Nov', 'value': 11}, {'label': 'Dez', 'value': 12}]

In [126]:
options_team = [{'label' : 'Todas as Equipes', 'value' : 0}]
for i in df['Equipe'].unique():
    options_team.append({'label' : i, 'value' : i})

In [127]:
options_team = sorted(options_team, key = lambda x: x['value'])

TypeError: '<' not supported between instances of 'str' and 'int'

In [128]:
options_team

[{'label': 'Todas as Equipes', 'value': 0},
 {'label': 'Equipe 1', 'value': 'Equipe 1'},
 {'label': 'Equipe 2', 'value': 'Equipe 2'},
 {'label': 'Equipe 3', 'value': 'Equipe 3'},
 {'label': 'Equipe 4', 'value': 'Equipe 4'}]

In [129]:
def month_filter(month): 
    if month == 0: 
        mask = df['Mês'].isin(df['Mês'].unique())
    else: 
        mask = df['Mês'].isin([month])
    return mask 

def team_filter(equipe): 
    if equipe == 0: 
        mask = df['Equipe'].isin(df['Equipe'].unique())
    else: 
        mask = df['Equipe'].isin([equipe])
    return mask

In [130]:
month_mask = month_filter(1)
df_filtrado_full = df.loc[month_mask]

In [131]:
df_filtrado_full

,Status de Pagamento,Dia,Mês,Meio de Propaganda,Valor Pago,Chamadas Realizadas,Duração da chamada,Modelo de Treinamento,Nivel de Treinamento,Código de Área,Equipe,Consultor
17,1,12,1,Televisão,11000000,1,02:00,GK,Pre. L3,C8,Equipe 2,Laura
47,1,12,1,Televisão,11000000,1,02:00,GK,Pre. L3,C8,Equipe 2,Laura
100,1,11,1,Google Ad,20000000,2,02:00,CNI,Fndn. L3,A1,Equipe 4,Bernardo
101,1,14,1,Google Ad,15000000,2,02:00,GK,Pre. L3,A1,Equipe 2,Laura
118,1,11,1,Google Ad,20000000,2,02:00,CNI,Fndn. L3,A1,Equipe 4,Bernardo
...,...,...,...,...,...,...,...,...,...,...,...,...
1144,0,13,1,Televisão,0,2,09:15,NaN,NaN,B12,Equipe 4,Bernardo
1145,1,12,1,Facebook,12000000,3,09:36,GK,KJI. L4,A1,Equipe 3,Sophia
1153,1,12,1,Facebook,12000000,3,09:36,GK,KJI. L4,A1,Equipe 3,Sophia
1190,1,17,1,Website,38000000,4,12:45,BE,Fndn. L5,A2,Equipe 2,Helena
1198,1,17,1,Website,38000000,4,12:45,BE,Fndn. L5,A2,Equipe 2,Helena

In [138]:
df_equipe_valor = df_filtrado_full.groupby('Equipe')['Valor Pago'].sum().reset_index()

In [139]:
df_equipe_valor

     Equipe  Valor Pago
0  Equipe 1   176000000
1  Equipe 2   418000000
2  Equipe 3   118000000
3  Equipe 4   272000000

In [140]:
fig_graph6 = go.Figure()

fig_graph6.add_trace(go.Pie(labels=df_equipe_valor['Equipe'].unique(), values=df_equipe_valor['Valor Pago'], hole=.6))

In [133]:
df_equipe_valor

     Equipe  Valor Pago
0  Equipe 1   176000000
1  Equipe 2   418000000
2  Equipe 3   118000000
3  Equipe 4   272000000

In [ ]:
month_mask = month_filter(1)
team_mask = team_filter("Equipe 1")
df_filtrado_full = df.loc[month_mask].loc[team_mask]

In [ ]:
df_filtrado_full

In [ ]:
df_consultor = df_filtrado_full.groupby(['Consultor', 'Equipe'])['Valor Pago'].sum()

In [ ]:
df_consultor

In [ ]:
df_consultor.sort_values(ascending=False, inplace=True)

In [ ]:
df_consultor

In [ ]:
df_consultor = df_consultor.reset_index()

In [ ]:
df_consultor

## Gerando DF1 -> Vendas por Equipe

In [ ]:
df1 = df.groupby('Equipe')['Valor Pago'].sum().reset_index()

In [ ]:
df1

In [ ]:
fig1 = go.Figure(
    go.Bar(
        x = df1['Valor Pago'],
        y = df1['Equipe'], 
        orientation='h', 
        text=df1['Valor Pago']
    )
)

In [ ]:
fig1

## Gerando DF2 -> Chamadas por Dia

In [ ]:
df2 = df.groupby('Dia')['Chamadas Realizadas'].sum().reset_index()

In [ ]:
fig2 = go.Figure(go.Bar(
    x=df2['Dia'], y=df2['Chamadas Realizadas']))

In [ ]:
fig2

## Gerando DF3 -> Chamadas por Mês

In [ ]:
df3 = df.groupby('Mês')['Chamadas Realizadas'].sum().reset_index()

In [ ]:
fig3 = go.Figure(go.Bar(
    x=df3['Mês'], y=df3['Chamadas Realizadas']))

In [ ]:
fig3

## Gerando DF4 -> Valores pagos por meio de propaganda

In [141]:
df4 = df.groupby(['Meio de Propaganda', 'Mês'])['Valor Pago'].sum().reset_index()

In [142]:
fig4 = px.line(df4, y="Valor Pago", x="Mês", color="Meio de Propaganda")
fig4

## Gerando DF5 -> Propaganda em PieChart // talvez botar no msm card

In [ ]:
df5 = df.groupby('Meio de Propaganda')['Valor Pago'].sum().reset_index()

In [ ]:
fig5 = go.Figure()
fig5.add_trace(go.Pie(labels=df5['Meio de Propaganda'], values=df5['Valor Pago'], hole=.7))

## Gerando DF6 -> Ganhos por Mês + segregação por equipe

In [ ]:
df6 = df.groupby(['Mês', 'Equipe'])['Valor Pago'].sum().reset_index()
df6_group = df.groupby('Mês')['Valor Pago'].sum().reset_index()

In [ ]:
fig5 = px.line(df6, y="Valor Pago", x="Mês", color="Equipe")
fig5.add_trace(go.Scatter(y=df6_group["Valor Pago"], x=df6_group["Mês"], mode='lines+markers', fill='tonexty', fillcolor='rgba(255, 0, 0, 0.2)', name='Total de Vendas'))

## Gerando DF7 -> Pagos e não Pagos

In [ ]:
df7 = df.groupby('Status de Pagamento')['Chamadas Realizadas'].sum()

In [ ]:
fig6 = go.Figure()
fig6.add_trace(go.Pie(labels=['Não Pago', 'Pago'], values=df7, hole=.6))

## INDICATORS

In [ ]:
df8 = df.groupby(['Consultor', 'Equipe'])['Valor Pago'].sum()

In [ ]:
df8.sort_values(ascending=False, inplace=True)

In [ ]:
df8 = df8.reset_index()

In [ ]:
df8

In [ ]:
fig8 = go.Figure()
fig8.add_trace(go.Indicator(mode='number+delta',
        title = {"text": f"<span style='font-size:150%'>{df8['Consultor'].iloc[0]} - Top Consultant</span><br><span style='font-size:70%'>Em vendas - em relação a média</span><br>"},
        value = df8['Valor Pago'].iloc[0],
        number = {'prefix': "R$"},
        delta = {'relative': True, 'valueformat': '.1%', 'reference': df8['Valor Pago'].mean()}
))

#### Indicators - Melhor Equipe

In [ ]:
df9 = df.groupby('Equipe')['Valor Pago'].sum()

In [ ]:
df9.sort_values(ascending=False, inplace=True)

In [ ]:
df9 = df9.reset_index()

In [ ]:
df9

In [ ]:
fig8 = go.Figure()
fig8.add_trace(go.Indicator(mode='number+delta',
        title = {"text": f"<span style='font-size:150%'>{df9['Equipe'].iloc[0]} - Top Team</span><br><span style='font-size:70%'>Em vendas - em relação a média</span><br>"},
        value = df9['Valor Pago'].iloc[0],
        number = {'prefix': "R$"},
        delta = {'relative': True, 'valueformat': '.1%', 'reference': df9['Valor Pago'].mean()}
))

#### Indicators - Ganhos Totais

In [ ]:
fig9 = go.Figure()
fig9.add_trace(go.Indicator(mode='number',
        title = {"text": f"<span style='font-size:150%'>Valor Total</span><br><span style='font-size:70%'>Em Reais</span><br>"},
        value = df['Valor Pago'].sum(),
        number = {'prefix': "R$"}
))

#### Indicators - Total de Chamadas

In [ ]:
fig10 = go.Figure()
fig10.add_trace(go.Indicator(mode='number',
        title = {"text": f"<span style='font-size:150%'>Chamadas Realizadas</span>"},
        value = len(df[df['Status de Pagamento'] == 1])
))

#### Top Consultant per Equipa e seus valores de venda

In [ ]:
df12 = df.groupby(['Equipe', 'Consultor'])['Valor Pago'].sum().reset_index()

In [ ]:
df13 = df.groupby(['Equipe', 'Consultor'])['Valor Pago'].sum()

In [ ]:
df13 = df13.sort_values(ascending=False)

In [ ]:
df13 = df13.groupby('Equipe').head(1).reset_index()

In [ ]:
df13

#### Top consultores + equipe por valor - PieChart

In [ ]:
fig13 = go.Figure(go.Pie(labels=df13['Consultor'] + ' - ' + df13['Equipe'], values=df13['Valor Pago'], hole=.6))
fig13